"""
Test server for serving adversarial HTML pages to Atlas browser.
Runs a local Flask server that hosts attack pages for red teaming.
"""
import logging
from pathlib import Path
from flask import Flask, send_from_directory, render_template_string
from threading import Thread
import time

logger = logging.getLogger(__name__)

# Create Flask app
app = Flask(__name__)

# Directory where test pages are stored
TEST_PAGES_DIR = Path(__file__).parent / "test_pages"


@app.route('/')
def index():
    """Landing page listing all available test pages."""
    test_pages = list(TEST_PAGES_DIR.glob("*.html"))
    
    html = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Atlas Red Team Test Server</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
            }
            h1 { color: #e74c3c; }
            .warning {
                background: #fff3cd;
                border: 2px solid #ffc107;
                padding: 15px;
                margin: 20px 0;
                border-radius: 5px;
            }
            ul { list-style: none; padding: 0; }
            li {
                background: white;
                margin: 10px 0;
                padding: 15px;
                border-radius: 5px;
                border-left: 4px solid #3498db;
            }
            a {
                text-decoration: none;
                color: #3498db;
                font-weight: bold;
            }
            a:hover { color: #2980b9; }
            .description {
                color: #666;
                font-size: 14px;
                margin-top: 5px;
            }
        </style>
    </head>
    <body>
        <h1>🔴 Atlas Red Team Test Server</h1>
        
        <div class="warning">
            <strong>⚠️ WARNING:</strong> This server hosts adversarial content designed for 
            security testing only. Do not use these pages maliciously or against systems 
            you don't have permission to test.
        </div>
        
        <h2>Available Test Pages</h2>
        <ul>
    """
    
    # Add links to test pages
    for page in test_pages:
        page_name = page.stem
        html += f"""
            <li>
                <a href="/test/{page_name}">{page_name}</a>
                <div class="description">Attack vector: {page_name.replace('_', ' ').title()}</div>
            </li>
        """
    
    html += """
        </ul>
        
        <h2>Server Information</h2>
        <p>Server: Flask Test Server</p>
        <p>Purpose: Atlas Browser Red Team Testing</p>
        <p>Status: <span style="color: green;">Running</span></p>
        
        <p style="margin-top: 40px; color: #999; font-size: 12px;">
            Generated by Atlas Red Teaming Harness
        </p>
    </body>
    </html>
    """
    
    return html


@app.route('/test/<page_name>')
def serve_test_page(page_name):
    """Serve a specific test page."""
    file_path = TEST_PAGES_DIR / f"{page_name}.html"
    
    if file_path.exists():
        return send_from_directory(TEST_PAGES_DIR, f"{page_name}.html")
    else:
        return f"Test page '{page_name}' not found", 404


@app.route('/api/log', methods=['POST'])
def log_interaction():
    """Endpoint for test pages to log interactions."""
    from flask import request
    data = request.get_json()
    logger.info(f"Browser interaction logged: {data}")
    return {"status": "logged"}


class TestServer:
    """Manages the test server lifecycle."""
    
    def __init__(self, host: str = "127.0.0.1", port: int = 8888):
        self.host = host
        self.port = port
        self.thread = None
        self.running = False
    
    def start(self):
        """Start the server in a background thread."""
        if self.running:
            logger.warning("Server already running")
            return
        
        logger.info(f"Starting test server on http://{self.host}:{self.port}")
        
        self.running = True
        self.thread = Thread(target=self._run, daemon=True)
        self.thread.start()
        
        # Wait for server to start
        time.sleep(2)
        logger.info(f"✓ Test server running at http://{self.host}:{self.port}")
    
    def _run(self):
        """Run the Flask server."""
        app.run(host=self.host, port=self.port, debug=False, use_reloader=False)
    
    def stop(self):
        """Stop the server."""
        self.running = False
        logger.info("Test server stopped")
    
    def get_url(self, page: str = "") -> str:
        """Get the URL for a test page."""
        if page:
            return f"http://{self.host}:{self.port}/test/{page}"
        return f"http://{self.host}:{self.port}"


if __name__ == "__main__":
    # Run server directly
    server = TestServer()
    try:
        server.start()
        print(f"\n{'='*60}")
        print("Atlas Red Team Test Server")
        print(f"{'='*60}")
        print(f"\nServer running at: {server.get_url()}")
        print("\nAvailable at:")
        print(f"  - Index: {server.get_url()}")
        print(f"  - Test pages: {server.get_url('PAGE_NAME')}")
        print("\nPress Ctrl+C to stop")
        print(f"{'='*60}\n")
        
        # Keep running
        while True:
            time.sleep(1)
            
    except KeyboardInterrupt:
        print("\nStopping server...")
        server.stop()

